#!/usr/bin/env bash

keylogger_dir_path=$(find ~ -name keylogger | head -n 1)
cd "$keylogger_dir_path" || { echo Not found "$keylogger_dir_path"; exit; }

if [[ $(ls | grep venv) ]]
then
  . venv/bin/activate
else
  echo Creating a virtual environment. Wait.
  virtualenv venv -q -p python3.10.4
  . venv/bin/activate
  pip install -qr requirements.txt
fi

python3 src/main.py "$@"